name: Gitleaks Security Scan


on:
  push:
    branches: [main,fix/security-JeremyBitton]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # GitLeaks scan
      - uses: zricethezav/gitleaks-action@v1
        with:
          args: "--redact --exit-code 1"