name: Gitleaks Security Scan

gitleaks:
  name: 1. Scan de Secrets (Gitleaks)
  runs-on: ubuntu-latest
  steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Lancer Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITLEAKS_ENABLE_EXIT_ONE: "true"
      with:
        format: sarif
        report_path: gitleaks-report.sarif

    - name: Uploader le rapport SARIF de Gitleaks
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: gitleaks-report.sarif