name: Snyk Security Scan
snyk:
  name: 3. Scan Applicatif (Snyk)
  runs-on: ubuntu-latest
  steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Mettre en place Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Lancer Snyk (Dépendances Applicatives)
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=high --sarif-file-output=snyk-deps.sarif --fail-on=all

    - name: Lancer Snyk (Code SAST)
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: code test
        args: --sarif-file-output=snyk-code.sarif

    - name: Uploader le rapport SARIF (Dépendances)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-deps.sarif

    - name: Uploader le rapport SARIF (Code SAST)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-code.sarif