name: Trivy Security Scan
trivy:
  name: 2. Scan de Vulnérabilités & IaC (Trivy)
  runs-on: ubuntu-latest
  steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Lancer Trivy FS Scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        scan-ref: './'

        scanners: 'vuln,config,secret'

        format: 'sarif'
        output: 'trivy-report.sarif'

        exit-code: '1'
        severity: 'HIGH,CRITICAL'

        ignore-unfixed: true

    - name: Uploader le rapport SARIF de Trivy
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-report.sarif'